app:
  name: hasher
image:
  repository: dockercoins/hasher
  tag: v0.2
  health:
    livenessProbe:
      httpGet:
        path: /
        port: container-port
    readinessProbe:
      httpGet:
        path: /
        port: container-port
