apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
{{ include "single.labels" . | indent 4 }}
{{ include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: service-port
      port: {{ .Values.service.port }}
      targetPort: container-port
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
